/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4UserGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4UserGet200ResponseData{}

// V4UserGet200ResponseData struct for V4UserGet200ResponseData
type V4UserGet200ResponseData struct {
	User *V4UserGet200ResponseDataUser `json:"user,omitempty"`
}

// NewV4UserGet200ResponseData instantiates a new V4UserGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4UserGet200ResponseData() *V4UserGet200ResponseData {
	this := V4UserGet200ResponseData{}
	return &this
}

// NewV4UserGet200ResponseDataWithDefaults instantiates a new V4UserGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4UserGet200ResponseDataWithDefaults() *V4UserGet200ResponseData {
	this := V4UserGet200ResponseData{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *V4UserGet200ResponseData) GetUser() V4UserGet200ResponseDataUser {
	if o == nil || IsNil(o.User) {
		var ret V4UserGet200ResponseDataUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseData) GetUserOk() (*V4UserGet200ResponseDataUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *V4UserGet200ResponseData) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given V4UserGet200ResponseDataUser and assigns it to the User field.
func (o *V4UserGet200ResponseData) SetUser(v V4UserGet200ResponseDataUser) {
	o.User = &v
}

func (o V4UserGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4UserGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableV4UserGet200ResponseData struct {
	value *V4UserGet200ResponseData
	isSet bool
}

func (v NullableV4UserGet200ResponseData) Get() *V4UserGet200ResponseData {
	return v.value
}

func (v *NullableV4UserGet200ResponseData) Set(val *V4UserGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4UserGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4UserGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4UserGet200ResponseData(val *V4UserGet200ResponseData) *NullableV4UserGet200ResponseData {
	return &NullableV4UserGet200ResponseData{value: val, isSet: true}
}

func (v NullableV4UserGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4UserGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
