/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4LinkInfosGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4LinkInfosGet200ResponseData{}

// V4LinkInfosGet200ResponseData struct for V4LinkInfosGet200ResponseData
type V4LinkInfosGet200ResponseData struct {
	// Array of info objects
	Infos []V4LinkInfosGet200ResponseDataInfosInner `json:"infos,omitempty"`
}

// NewV4LinkInfosGet200ResponseData instantiates a new V4LinkInfosGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4LinkInfosGet200ResponseData() *V4LinkInfosGet200ResponseData {
	this := V4LinkInfosGet200ResponseData{}
	return &this
}

// NewV4LinkInfosGet200ResponseDataWithDefaults instantiates a new V4LinkInfosGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4LinkInfosGet200ResponseDataWithDefaults() *V4LinkInfosGet200ResponseData {
	this := V4LinkInfosGet200ResponseData{}
	return &this
}

// GetInfos returns the Infos field value if set, zero value otherwise.
func (o *V4LinkInfosGet200ResponseData) GetInfos() []V4LinkInfosGet200ResponseDataInfosInner {
	if o == nil || IsNil(o.Infos) {
		var ret []V4LinkInfosGet200ResponseDataInfosInner
		return ret
	}
	return o.Infos
}

// GetInfosOk returns a tuple with the Infos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4LinkInfosGet200ResponseData) GetInfosOk() ([]V4LinkInfosGet200ResponseDataInfosInner, bool) {
	if o == nil || IsNil(o.Infos) {
		return nil, false
	}
	return o.Infos, true
}

// HasInfos returns a boolean if a field has been set.
func (o *V4LinkInfosGet200ResponseData) HasInfos() bool {
	if o != nil && !IsNil(o.Infos) {
		return true
	}

	return false
}

// SetInfos gets a reference to the given []V4LinkInfosGet200ResponseDataInfosInner and assigns it to the Infos field.
func (o *V4LinkInfosGet200ResponseData) SetInfos(v []V4LinkInfosGet200ResponseDataInfosInner) {
	o.Infos = v
}

func (o V4LinkInfosGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4LinkInfosGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Infos) {
		toSerialize["infos"] = o.Infos
	}
	return toSerialize, nil
}

type NullableV4LinkInfosGet200ResponseData struct {
	value *V4LinkInfosGet200ResponseData
	isSet bool
}

func (v NullableV4LinkInfosGet200ResponseData) Get() *V4LinkInfosGet200ResponseData {
	return v.value
}

func (v *NullableV4LinkInfosGet200ResponseData) Set(val *V4LinkInfosGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4LinkInfosGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4LinkInfosGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4LinkInfosGet200ResponseData(val *V4LinkInfosGet200ResponseData) *NullableV4LinkInfosGet200ResponseData {
	return &NullableV4LinkInfosGet200ResponseData{value: val, isSet: true}
}

func (v NullableV4LinkInfosGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4LinkInfosGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
