/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V41MagnetStatusGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V41MagnetStatusGet200ResponseData{}

// V41MagnetStatusGet200ResponseData struct for V41MagnetStatusGet200ResponseData
type V41MagnetStatusGet200ResponseData struct {
	Magnets []V41MagnetStatusGet200ResponseDataMagnetsInner `json:"magnets,omitempty"`
}

// NewV41MagnetStatusGet200ResponseData instantiates a new V41MagnetStatusGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV41MagnetStatusGet200ResponseData() *V41MagnetStatusGet200ResponseData {
	this := V41MagnetStatusGet200ResponseData{}
	return &this
}

// NewV41MagnetStatusGet200ResponseDataWithDefaults instantiates a new V41MagnetStatusGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV41MagnetStatusGet200ResponseDataWithDefaults() *V41MagnetStatusGet200ResponseData {
	this := V41MagnetStatusGet200ResponseData{}
	return &this
}

// GetMagnets returns the Magnets field value if set, zero value otherwise.
func (o *V41MagnetStatusGet200ResponseData) GetMagnets() []V41MagnetStatusGet200ResponseDataMagnetsInner {
	if o == nil || IsNil(o.Magnets) {
		var ret []V41MagnetStatusGet200ResponseDataMagnetsInner
		return ret
	}
	return o.Magnets
}

// GetMagnetsOk returns a tuple with the Magnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V41MagnetStatusGet200ResponseData) GetMagnetsOk() ([]V41MagnetStatusGet200ResponseDataMagnetsInner, bool) {
	if o == nil || IsNil(o.Magnets) {
		return nil, false
	}
	return o.Magnets, true
}

// HasMagnets returns a boolean if a field has been set.
func (o *V41MagnetStatusGet200ResponseData) HasMagnets() bool {
	if o != nil && !IsNil(o.Magnets) {
		return true
	}

	return false
}

// SetMagnets gets a reference to the given []V41MagnetStatusGet200ResponseDataMagnetsInner and assigns it to the Magnets field.
func (o *V41MagnetStatusGet200ResponseData) SetMagnets(v []V41MagnetStatusGet200ResponseDataMagnetsInner) {
	o.Magnets = v
}

func (o V41MagnetStatusGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V41MagnetStatusGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Magnets) {
		toSerialize["magnets"] = o.Magnets
	}
	return toSerialize, nil
}

type NullableV41MagnetStatusGet200ResponseData struct {
	value *V41MagnetStatusGet200ResponseData
	isSet bool
}

func (v NullableV41MagnetStatusGet200ResponseData) Get() *V41MagnetStatusGet200ResponseData {
	return v.value
}

func (v *NullableV41MagnetStatusGet200ResponseData) Set(val *V41MagnetStatusGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV41MagnetStatusGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV41MagnetStatusGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV41MagnetStatusGet200ResponseData(val *V41MagnetStatusGet200ResponseData) *NullableV41MagnetStatusGet200ResponseData {
	return &NullableV41MagnetStatusGet200ResponseData{value: val, isSet: true}
}

func (v NullableV41MagnetStatusGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV41MagnetStatusGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
