/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4MagnetUploadGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4MagnetUploadGet200ResponseData{}

// V4MagnetUploadGet200ResponseData struct for V4MagnetUploadGet200ResponseData
type V4MagnetUploadGet200ResponseData struct {
	Magnets []V4MagnetUploadGet200ResponseDataMagnetsInner `json:"magnets,omitempty"`
}

// NewV4MagnetUploadGet200ResponseData instantiates a new V4MagnetUploadGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4MagnetUploadGet200ResponseData() *V4MagnetUploadGet200ResponseData {
	this := V4MagnetUploadGet200ResponseData{}
	return &this
}

// NewV4MagnetUploadGet200ResponseDataWithDefaults instantiates a new V4MagnetUploadGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4MagnetUploadGet200ResponseDataWithDefaults() *V4MagnetUploadGet200ResponseData {
	this := V4MagnetUploadGet200ResponseData{}
	return &this
}

// GetMagnets returns the Magnets field value if set, zero value otherwise.
func (o *V4MagnetUploadGet200ResponseData) GetMagnets() []V4MagnetUploadGet200ResponseDataMagnetsInner {
	if o == nil || IsNil(o.Magnets) {
		var ret []V4MagnetUploadGet200ResponseDataMagnetsInner
		return ret
	}
	return o.Magnets
}

// GetMagnetsOk returns a tuple with the Magnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadGet200ResponseData) GetMagnetsOk() ([]V4MagnetUploadGet200ResponseDataMagnetsInner, bool) {
	if o == nil || IsNil(o.Magnets) {
		return nil, false
	}
	return o.Magnets, true
}

// HasMagnets returns a boolean if a field has been set.
func (o *V4MagnetUploadGet200ResponseData) HasMagnets() bool {
	if o != nil && !IsNil(o.Magnets) {
		return true
	}

	return false
}

// SetMagnets gets a reference to the given []V4MagnetUploadGet200ResponseDataMagnetsInner and assigns it to the Magnets field.
func (o *V4MagnetUploadGet200ResponseData) SetMagnets(v []V4MagnetUploadGet200ResponseDataMagnetsInner) {
	o.Magnets = v
}

func (o V4MagnetUploadGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4MagnetUploadGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Magnets) {
		toSerialize["magnets"] = o.Magnets
	}
	return toSerialize, nil
}

type NullableV4MagnetUploadGet200ResponseData struct {
	value *V4MagnetUploadGet200ResponseData
	isSet bool
}

func (v NullableV4MagnetUploadGet200ResponseData) Get() *V4MagnetUploadGet200ResponseData {
	return v.value
}

func (v *NullableV4MagnetUploadGet200ResponseData) Set(val *V4MagnetUploadGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4MagnetUploadGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4MagnetUploadGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4MagnetUploadGet200ResponseData(val *V4MagnetUploadGet200ResponseData) *NullableV4MagnetUploadGet200ResponseData {
	return &NullableV4MagnetUploadGet200ResponseData{value: val, isSet: true}
}

func (v NullableV4MagnetUploadGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4MagnetUploadGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
