/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4MagnetUploadFilePost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4MagnetUploadFilePost200ResponseData{}

// V4MagnetUploadFilePost200ResponseData struct for V4MagnetUploadFilePost200ResponseData
type V4MagnetUploadFilePost200ResponseData struct {
	Files []V4MagnetUploadFilePost200ResponseDataFilesInner `json:"files,omitempty"`
}

// NewV4MagnetUploadFilePost200ResponseData instantiates a new V4MagnetUploadFilePost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4MagnetUploadFilePost200ResponseData() *V4MagnetUploadFilePost200ResponseData {
	this := V4MagnetUploadFilePost200ResponseData{}
	return &this
}

// NewV4MagnetUploadFilePost200ResponseDataWithDefaults instantiates a new V4MagnetUploadFilePost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4MagnetUploadFilePost200ResponseDataWithDefaults() *V4MagnetUploadFilePost200ResponseData {
	this := V4MagnetUploadFilePost200ResponseData{}
	return &this
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *V4MagnetUploadFilePost200ResponseData) GetFiles() []V4MagnetUploadFilePost200ResponseDataFilesInner {
	if o == nil || IsNil(o.Files) {
		var ret []V4MagnetUploadFilePost200ResponseDataFilesInner
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadFilePost200ResponseData) GetFilesOk() ([]V4MagnetUploadFilePost200ResponseDataFilesInner, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *V4MagnetUploadFilePost200ResponseData) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []V4MagnetUploadFilePost200ResponseDataFilesInner and assigns it to the Files field.
func (o *V4MagnetUploadFilePost200ResponseData) SetFiles(v []V4MagnetUploadFilePost200ResponseDataFilesInner) {
	o.Files = v
}

func (o V4MagnetUploadFilePost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4MagnetUploadFilePost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	return toSerialize, nil
}

type NullableV4MagnetUploadFilePost200ResponseData struct {
	value *V4MagnetUploadFilePost200ResponseData
	isSet bool
}

func (v NullableV4MagnetUploadFilePost200ResponseData) Get() *V4MagnetUploadFilePost200ResponseData {
	return v.value
}

func (v *NullableV4MagnetUploadFilePost200ResponseData) Set(val *V4MagnetUploadFilePost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4MagnetUploadFilePost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4MagnetUploadFilePost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4MagnetUploadFilePost200ResponseData(val *V4MagnetUploadFilePost200ResponseData) *NullableV4MagnetUploadFilePost200ResponseData {
	return &NullableV4MagnetUploadFilePost200ResponseData{value: val, isSet: true}
}

func (v NullableV4MagnetUploadFilePost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4MagnetUploadFilePost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
