/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4UserLinksGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4UserLinksGet200ResponseData{}

// V4UserLinksGet200ResponseData struct for V4UserLinksGet200ResponseData
type V4UserLinksGet200ResponseData struct {
	Links []V4UserLinksGet200ResponseDataLinksInner `json:"links,omitempty"`
}

// NewV4UserLinksGet200ResponseData instantiates a new V4UserLinksGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4UserLinksGet200ResponseData() *V4UserLinksGet200ResponseData {
	this := V4UserLinksGet200ResponseData{}
	return &this
}

// NewV4UserLinksGet200ResponseDataWithDefaults instantiates a new V4UserLinksGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4UserLinksGet200ResponseDataWithDefaults() *V4UserLinksGet200ResponseData {
	this := V4UserLinksGet200ResponseData{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *V4UserLinksGet200ResponseData) GetLinks() []V4UserLinksGet200ResponseDataLinksInner {
	if o == nil || IsNil(o.Links) {
		var ret []V4UserLinksGet200ResponseDataLinksInner
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserLinksGet200ResponseData) GetLinksOk() ([]V4UserLinksGet200ResponseDataLinksInner, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *V4UserLinksGet200ResponseData) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []V4UserLinksGet200ResponseDataLinksInner and assigns it to the Links field.
func (o *V4UserLinksGet200ResponseData) SetLinks(v []V4UserLinksGet200ResponseDataLinksInner) {
	o.Links = v
}

func (o V4UserLinksGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4UserLinksGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableV4UserLinksGet200ResponseData struct {
	value *V4UserLinksGet200ResponseData
	isSet bool
}

func (v NullableV4UserLinksGet200ResponseData) Get() *V4UserLinksGet200ResponseData {
	return v.value
}

func (v *NullableV4UserLinksGet200ResponseData) Set(val *V4UserLinksGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4UserLinksGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4UserLinksGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4UserLinksGet200ResponseData(val *V4UserLinksGet200ResponseData) *NullableV4UserLinksGet200ResponseData {
	return &NullableV4UserLinksGet200ResponseData{value: val, isSet: true}
}

func (v NullableV4UserLinksGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4UserLinksGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
