/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4LinkRedirectorGet200ResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4LinkRedirectorGet200ResponseError{}

// V4LinkRedirectorGet200ResponseError struct for V4LinkRedirectorGet200ResponseError
type V4LinkRedirectorGet200ResponseError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewV4LinkRedirectorGet200ResponseError instantiates a new V4LinkRedirectorGet200ResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4LinkRedirectorGet200ResponseError() *V4LinkRedirectorGet200ResponseError {
	this := V4LinkRedirectorGet200ResponseError{}
	return &this
}

// NewV4LinkRedirectorGet200ResponseErrorWithDefaults instantiates a new V4LinkRedirectorGet200ResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4LinkRedirectorGet200ResponseErrorWithDefaults() *V4LinkRedirectorGet200ResponseError {
	this := V4LinkRedirectorGet200ResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *V4LinkRedirectorGet200ResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4LinkRedirectorGet200ResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *V4LinkRedirectorGet200ResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *V4LinkRedirectorGet200ResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V4LinkRedirectorGet200ResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4LinkRedirectorGet200ResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V4LinkRedirectorGet200ResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V4LinkRedirectorGet200ResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o V4LinkRedirectorGet200ResponseError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4LinkRedirectorGet200ResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableV4LinkRedirectorGet200ResponseError struct {
	value *V4LinkRedirectorGet200ResponseError
	isSet bool
}

func (v NullableV4LinkRedirectorGet200ResponseError) Get() *V4LinkRedirectorGet200ResponseError {
	return v.value
}

func (v *NullableV4LinkRedirectorGet200ResponseError) Set(val *V4LinkRedirectorGet200ResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableV4LinkRedirectorGet200ResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableV4LinkRedirectorGet200ResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4LinkRedirectorGet200ResponseError(val *V4LinkRedirectorGet200ResponseError) *NullableV4LinkRedirectorGet200ResponseError {
	return &NullableV4LinkRedirectorGet200ResponseError{value: val, isSet: true}
}

func (v NullableV4LinkRedirectorGet200ResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4LinkRedirectorGet200ResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
