/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4LinkRedirectorGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4LinkRedirectorGet200ResponseData{}

// V4LinkRedirectorGet200ResponseData struct for V4LinkRedirectorGet200ResponseData
type V4LinkRedirectorGet200ResponseData struct {
	// Link(s) extracted.
	Links []string `json:"links,omitempty"`
}

// NewV4LinkRedirectorGet200ResponseData instantiates a new V4LinkRedirectorGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4LinkRedirectorGet200ResponseData() *V4LinkRedirectorGet200ResponseData {
	this := V4LinkRedirectorGet200ResponseData{}
	return &this
}

// NewV4LinkRedirectorGet200ResponseDataWithDefaults instantiates a new V4LinkRedirectorGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4LinkRedirectorGet200ResponseDataWithDefaults() *V4LinkRedirectorGet200ResponseData {
	this := V4LinkRedirectorGet200ResponseData{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *V4LinkRedirectorGet200ResponseData) GetLinks() []string {
	if o == nil || IsNil(o.Links) {
		var ret []string
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4LinkRedirectorGet200ResponseData) GetLinksOk() ([]string, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *V4LinkRedirectorGet200ResponseData) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []string and assigns it to the Links field.
func (o *V4LinkRedirectorGet200ResponseData) SetLinks(v []string) {
	o.Links = v
}

func (o V4LinkRedirectorGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4LinkRedirectorGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableV4LinkRedirectorGet200ResponseData struct {
	value *V4LinkRedirectorGet200ResponseData
	isSet bool
}

func (v NullableV4LinkRedirectorGet200ResponseData) Get() *V4LinkRedirectorGet200ResponseData {
	return v.value
}

func (v *NullableV4LinkRedirectorGet200ResponseData) Set(val *V4LinkRedirectorGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4LinkRedirectorGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4LinkRedirectorGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4LinkRedirectorGet200ResponseData(val *V4LinkRedirectorGet200ResponseData) *NullableV4LinkRedirectorGet200ResponseData {
	return &NullableV4LinkRedirectorGet200ResponseData{value: val, isSet: true}
}

func (v NullableV4LinkRedirectorGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4LinkRedirectorGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
