/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4LinkDelayedGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4LinkDelayedGet200ResponseData{}

// V4LinkDelayedGet200ResponseData struct for V4LinkDelayedGet200ResponseData
type V4LinkDelayedGet200ResponseData struct {
	Status   *int64  `json:"status,omitempty"`
	TimeLeft *int64  `json:"time_left,omitempty"`
	Link     *string `json:"link,omitempty"`
}

// NewV4LinkDelayedGet200ResponseData instantiates a new V4LinkDelayedGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4LinkDelayedGet200ResponseData() *V4LinkDelayedGet200ResponseData {
	this := V4LinkDelayedGet200ResponseData{}
	return &this
}

// NewV4LinkDelayedGet200ResponseDataWithDefaults instantiates a new V4LinkDelayedGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4LinkDelayedGet200ResponseDataWithDefaults() *V4LinkDelayedGet200ResponseData {
	this := V4LinkDelayedGet200ResponseData{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V4LinkDelayedGet200ResponseData) GetStatus() int64 {
	if o == nil || IsNil(o.Status) {
		var ret int64
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4LinkDelayedGet200ResponseData) GetStatusOk() (*int64, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V4LinkDelayedGet200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int64 and assigns it to the Status field.
func (o *V4LinkDelayedGet200ResponseData) SetStatus(v int64) {
	o.Status = &v
}

// GetTimeLeft returns the TimeLeft field value if set, zero value otherwise.
func (o *V4LinkDelayedGet200ResponseData) GetTimeLeft() int64 {
	if o == nil || IsNil(o.TimeLeft) {
		var ret int64
		return ret
	}
	return *o.TimeLeft
}

// GetTimeLeftOk returns a tuple with the TimeLeft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4LinkDelayedGet200ResponseData) GetTimeLeftOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeLeft) {
		return nil, false
	}
	return o.TimeLeft, true
}

// HasTimeLeft returns a boolean if a field has been set.
func (o *V4LinkDelayedGet200ResponseData) HasTimeLeft() bool {
	if o != nil && !IsNil(o.TimeLeft) {
		return true
	}

	return false
}

// SetTimeLeft gets a reference to the given int64 and assigns it to the TimeLeft field.
func (o *V4LinkDelayedGet200ResponseData) SetTimeLeft(v int64) {
	o.TimeLeft = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *V4LinkDelayedGet200ResponseData) GetLink() string {
	if o == nil || IsNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4LinkDelayedGet200ResponseData) GetLinkOk() (*string, bool) {
	if o == nil || IsNil(o.Link) {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *V4LinkDelayedGet200ResponseData) HasLink() bool {
	if o != nil && !IsNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *V4LinkDelayedGet200ResponseData) SetLink(v string) {
	o.Link = &v
}

func (o V4LinkDelayedGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4LinkDelayedGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TimeLeft) {
		toSerialize["time_left"] = o.TimeLeft
	}
	if !IsNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	return toSerialize, nil
}

type NullableV4LinkDelayedGet200ResponseData struct {
	value *V4LinkDelayedGet200ResponseData
	isSet bool
}

func (v NullableV4LinkDelayedGet200ResponseData) Get() *V4LinkDelayedGet200ResponseData {
	return v.value
}

func (v *NullableV4LinkDelayedGet200ResponseData) Set(val *V4LinkDelayedGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4LinkDelayedGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4LinkDelayedGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4LinkDelayedGet200ResponseData(val *V4LinkDelayedGet200ResponseData) *NullableV4LinkDelayedGet200ResponseData {
	return &NullableV4LinkDelayedGet200ResponseData{value: val, isSet: true}
}

func (v NullableV4LinkDelayedGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4LinkDelayedGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
