/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4MagnetUploadFilePost200ResponseDataFilesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4MagnetUploadFilePost200ResponseDataFilesInner{}

// V4MagnetUploadFilePost200ResponseDataFilesInner struct for V4MagnetUploadFilePost200ResponseDataFilesInner
type V4MagnetUploadFilePost200ResponseDataFilesInner struct {
	File  *string                                               `json:"file,omitempty"`
	Hash  *string                                               `json:"hash,omitempty"`
	Name  *string                                               `json:"name,omitempty"`
	Size  *int64                                                `json:"size,omitempty"`
	Ready *bool                                                 `json:"ready,omitempty"`
	Id    *int64                                                `json:"id,omitempty"`
	Error *V4MagnetUploadFilePost200ResponseDataFilesInnerError `json:"error,omitempty"`
}

// NewV4MagnetUploadFilePost200ResponseDataFilesInner instantiates a new V4MagnetUploadFilePost200ResponseDataFilesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4MagnetUploadFilePost200ResponseDataFilesInner() *V4MagnetUploadFilePost200ResponseDataFilesInner {
	this := V4MagnetUploadFilePost200ResponseDataFilesInner{}
	return &this
}

// NewV4MagnetUploadFilePost200ResponseDataFilesInnerWithDefaults instantiates a new V4MagnetUploadFilePost200ResponseDataFilesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4MagnetUploadFilePost200ResponseDataFilesInnerWithDefaults() *V4MagnetUploadFilePost200ResponseDataFilesInner {
	this := V4MagnetUploadFilePost200ResponseDataFilesInner{}
	return &this
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetFile() string {
	if o == nil || IsNil(o.File) {
		var ret string
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetFileOk() (*string, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given string and assigns it to the File field.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) SetFile(v string) {
	o.File = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) SetHash(v string) {
	o.Hash = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) SetSize(v int64) {
	o.Size = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetReady() bool {
	if o == nil || IsNil(o.Ready) {
		var ret bool
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetReadyOk() (*bool, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) HasReady() bool {
	if o != nil && !IsNil(o.Ready) {
		return true
	}

	return false
}

// SetReady gets a reference to the given bool and assigns it to the Ready field.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) SetReady(v bool) {
	o.Ready = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) SetId(v int64) {
	o.Id = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetError() V4MagnetUploadFilePost200ResponseDataFilesInnerError {
	if o == nil || IsNil(o.Error) {
		var ret V4MagnetUploadFilePost200ResponseDataFilesInnerError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) GetErrorOk() (*V4MagnetUploadFilePost200ResponseDataFilesInnerError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given V4MagnetUploadFilePost200ResponseDataFilesInnerError and assigns it to the Error field.
func (o *V4MagnetUploadFilePost200ResponseDataFilesInner) SetError(v V4MagnetUploadFilePost200ResponseDataFilesInnerError) {
	o.Error = &v
}

func (o V4MagnetUploadFilePost200ResponseDataFilesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4MagnetUploadFilePost200ResponseDataFilesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Ready) {
		toSerialize["ready"] = o.Ready
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableV4MagnetUploadFilePost200ResponseDataFilesInner struct {
	value *V4MagnetUploadFilePost200ResponseDataFilesInner
	isSet bool
}

func (v NullableV4MagnetUploadFilePost200ResponseDataFilesInner) Get() *V4MagnetUploadFilePost200ResponseDataFilesInner {
	return v.value
}

func (v *NullableV4MagnetUploadFilePost200ResponseDataFilesInner) Set(val *V4MagnetUploadFilePost200ResponseDataFilesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV4MagnetUploadFilePost200ResponseDataFilesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV4MagnetUploadFilePost200ResponseDataFilesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4MagnetUploadFilePost200ResponseDataFilesInner(val *V4MagnetUploadFilePost200ResponseDataFilesInner) *NullableV4MagnetUploadFilePost200ResponseDataFilesInner {
	return &NullableV4MagnetUploadFilePost200ResponseDataFilesInner{value: val, isSet: true}
}

func (v NullableV4MagnetUploadFilePost200ResponseDataFilesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4MagnetUploadFilePost200ResponseDataFilesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
