/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4HostsDomainsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4HostsDomainsGet200ResponseData{}

// V4HostsDomainsGet200ResponseData struct for V4HostsDomainsGet200ResponseData
type V4HostsDomainsGet200ResponseData struct {
	Hosts       []string `json:"hosts,omitempty"`
	Streams     []string `json:"streams,omitempty"`
	Redirectors []string `json:"redirectors,omitempty"`
}

// NewV4HostsDomainsGet200ResponseData instantiates a new V4HostsDomainsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4HostsDomainsGet200ResponseData() *V4HostsDomainsGet200ResponseData {
	this := V4HostsDomainsGet200ResponseData{}
	return &this
}

// NewV4HostsDomainsGet200ResponseDataWithDefaults instantiates a new V4HostsDomainsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4HostsDomainsGet200ResponseDataWithDefaults() *V4HostsDomainsGet200ResponseData {
	this := V4HostsDomainsGet200ResponseData{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *V4HostsDomainsGet200ResponseData) GetHosts() []string {
	if o == nil || IsNil(o.Hosts) {
		var ret []string
		return ret
	}
	return o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4HostsDomainsGet200ResponseData) GetHostsOk() ([]string, bool) {
	if o == nil || IsNil(o.Hosts) {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *V4HostsDomainsGet200ResponseData) HasHosts() bool {
	if o != nil && !IsNil(o.Hosts) {
		return true
	}

	return false
}

// SetHosts gets a reference to the given []string and assigns it to the Hosts field.
func (o *V4HostsDomainsGet200ResponseData) SetHosts(v []string) {
	o.Hosts = v
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *V4HostsDomainsGet200ResponseData) GetStreams() []string {
	if o == nil || IsNil(o.Streams) {
		var ret []string
		return ret
	}
	return o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4HostsDomainsGet200ResponseData) GetStreamsOk() ([]string, bool) {
	if o == nil || IsNil(o.Streams) {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *V4HostsDomainsGet200ResponseData) HasStreams() bool {
	if o != nil && !IsNil(o.Streams) {
		return true
	}

	return false
}

// SetStreams gets a reference to the given []string and assigns it to the Streams field.
func (o *V4HostsDomainsGet200ResponseData) SetStreams(v []string) {
	o.Streams = v
}

// GetRedirectors returns the Redirectors field value if set, zero value otherwise.
func (o *V4HostsDomainsGet200ResponseData) GetRedirectors() []string {
	if o == nil || IsNil(o.Redirectors) {
		var ret []string
		return ret
	}
	return o.Redirectors
}

// GetRedirectorsOk returns a tuple with the Redirectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4HostsDomainsGet200ResponseData) GetRedirectorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Redirectors) {
		return nil, false
	}
	return o.Redirectors, true
}

// HasRedirectors returns a boolean if a field has been set.
func (o *V4HostsDomainsGet200ResponseData) HasRedirectors() bool {
	if o != nil && !IsNil(o.Redirectors) {
		return true
	}

	return false
}

// SetRedirectors gets a reference to the given []string and assigns it to the Redirectors field.
func (o *V4HostsDomainsGet200ResponseData) SetRedirectors(v []string) {
	o.Redirectors = v
}

func (o V4HostsDomainsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4HostsDomainsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hosts) {
		toSerialize["hosts"] = o.Hosts
	}
	if !IsNil(o.Streams) {
		toSerialize["streams"] = o.Streams
	}
	if !IsNil(o.Redirectors) {
		toSerialize["redirectors"] = o.Redirectors
	}
	return toSerialize, nil
}

type NullableV4HostsDomainsGet200ResponseData struct {
	value *V4HostsDomainsGet200ResponseData
	isSet bool
}

func (v NullableV4HostsDomainsGet200ResponseData) Get() *V4HostsDomainsGet200ResponseData {
	return v.value
}

func (v *NullableV4HostsDomainsGet200ResponseData) Set(val *V4HostsDomainsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4HostsDomainsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4HostsDomainsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4HostsDomainsGet200ResponseData(val *V4HostsDomainsGet200ResponseData) *NullableV4HostsDomainsGet200ResponseData {
	return &NullableV4HostsDomainsGet200ResponseData{value: val, isSet: true}
}

func (v NullableV4HostsDomainsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4HostsDomainsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
