/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4HostsPriorityGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4HostsPriorityGet200ResponseData{}

// V4HostsPriorityGet200ResponseData struct for V4HostsPriorityGet200ResponseData
type V4HostsPriorityGet200ResponseData struct {
	Hosts *map[string]int64 `json:"hosts,omitempty"`
}

// NewV4HostsPriorityGet200ResponseData instantiates a new V4HostsPriorityGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4HostsPriorityGet200ResponseData() *V4HostsPriorityGet200ResponseData {
	this := V4HostsPriorityGet200ResponseData{}
	return &this
}

// NewV4HostsPriorityGet200ResponseDataWithDefaults instantiates a new V4HostsPriorityGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4HostsPriorityGet200ResponseDataWithDefaults() *V4HostsPriorityGet200ResponseData {
	this := V4HostsPriorityGet200ResponseData{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *V4HostsPriorityGet200ResponseData) GetHosts() map[string]int64 {
	if o == nil || IsNil(o.Hosts) {
		var ret map[string]int64
		return ret
	}
	return *o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4HostsPriorityGet200ResponseData) GetHostsOk() (*map[string]int64, bool) {
	if o == nil || IsNil(o.Hosts) {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *V4HostsPriorityGet200ResponseData) HasHosts() bool {
	if o != nil && !IsNil(o.Hosts) {
		return true
	}

	return false
}

// SetHosts gets a reference to the given map[string]int64 and assigns it to the Hosts field.
func (o *V4HostsPriorityGet200ResponseData) SetHosts(v map[string]int64) {
	o.Hosts = &v
}

func (o V4HostsPriorityGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4HostsPriorityGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hosts) {
		toSerialize["hosts"] = o.Hosts
	}
	return toSerialize, nil
}

type NullableV4HostsPriorityGet200ResponseData struct {
	value *V4HostsPriorityGet200ResponseData
	isSet bool
}

func (v NullableV4HostsPriorityGet200ResponseData) Get() *V4HostsPriorityGet200ResponseData {
	return v.value
}

func (v *NullableV4HostsPriorityGet200ResponseData) Set(val *V4HostsPriorityGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV4HostsPriorityGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV4HostsPriorityGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4HostsPriorityGet200ResponseData(val *V4HostsPriorityGet200ResponseData) *NullableV4HostsPriorityGet200ResponseData {
	return &NullableV4HostsPriorityGet200ResponseData{value: val, isSet: true}
}

func (v NullableV4HostsPriorityGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4HostsPriorityGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
