/*
Alldebrid API

Welcome to the Alldebrid API! You can use this API to access various Alldebrid services from custom applications or scripts.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the V4UserGet200ResponseDataUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V4UserGet200ResponseDataUser{}

// V4UserGet200ResponseDataUser struct for V4UserGet200ResponseDataUser
type V4UserGet200ResponseDataUser struct {
	Username             *string           `json:"username,omitempty"`
	Email                *string           `json:"email,omitempty"`
	IsPremium            *bool             `json:"isPremium,omitempty"`
	IsSubscribed         *bool             `json:"isSubscribed,omitempty"`
	IsTrial              *bool             `json:"isTrial,omitempty"`
	PremiumUntil         *int64            `json:"premiumUntil,omitempty"`
	Lang                 *string           `json:"lang,omitempty"`
	PreferedDomain       *string           `json:"preferedDomain,omitempty"`
	FidelityPoints       *int64            `json:"fidelityPoints,omitempty"`
	LimitedHostersQuotas *map[string]int64 `json:"limitedHostersQuotas,omitempty"`
	Notifications        []string          `json:"notifications,omitempty"`
}

// NewV4UserGet200ResponseDataUser instantiates a new V4UserGet200ResponseDataUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4UserGet200ResponseDataUser() *V4UserGet200ResponseDataUser {
	this := V4UserGet200ResponseDataUser{}
	return &this
}

// NewV4UserGet200ResponseDataUserWithDefaults instantiates a new V4UserGet200ResponseDataUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4UserGet200ResponseDataUserWithDefaults() *V4UserGet200ResponseDataUser {
	this := V4UserGet200ResponseDataUser{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *V4UserGet200ResponseDataUser) SetUsername(v string) {
	o.Username = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *V4UserGet200ResponseDataUser) SetEmail(v string) {
	o.Email = &v
}

// GetIsPremium returns the IsPremium field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetIsPremium() bool {
	if o == nil || IsNil(o.IsPremium) {
		var ret bool
		return ret
	}
	return *o.IsPremium
}

// GetIsPremiumOk returns a tuple with the IsPremium field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetIsPremiumOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPremium) {
		return nil, false
	}
	return o.IsPremium, true
}

// HasIsPremium returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasIsPremium() bool {
	if o != nil && !IsNil(o.IsPremium) {
		return true
	}

	return false
}

// SetIsPremium gets a reference to the given bool and assigns it to the IsPremium field.
func (o *V4UserGet200ResponseDataUser) SetIsPremium(v bool) {
	o.IsPremium = &v
}

// GetIsSubscribed returns the IsSubscribed field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetIsSubscribed() bool {
	if o == nil || IsNil(o.IsSubscribed) {
		var ret bool
		return ret
	}
	return *o.IsSubscribed
}

// GetIsSubscribedOk returns a tuple with the IsSubscribed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetIsSubscribedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSubscribed) {
		return nil, false
	}
	return o.IsSubscribed, true
}

// HasIsSubscribed returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasIsSubscribed() bool {
	if o != nil && !IsNil(o.IsSubscribed) {
		return true
	}

	return false
}

// SetIsSubscribed gets a reference to the given bool and assigns it to the IsSubscribed field.
func (o *V4UserGet200ResponseDataUser) SetIsSubscribed(v bool) {
	o.IsSubscribed = &v
}

// GetIsTrial returns the IsTrial field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetIsTrial() bool {
	if o == nil || IsNil(o.IsTrial) {
		var ret bool
		return ret
	}
	return *o.IsTrial
}

// GetIsTrialOk returns a tuple with the IsTrial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetIsTrialOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTrial) {
		return nil, false
	}
	return o.IsTrial, true
}

// HasIsTrial returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasIsTrial() bool {
	if o != nil && !IsNil(o.IsTrial) {
		return true
	}

	return false
}

// SetIsTrial gets a reference to the given bool and assigns it to the IsTrial field.
func (o *V4UserGet200ResponseDataUser) SetIsTrial(v bool) {
	o.IsTrial = &v
}

// GetPremiumUntil returns the PremiumUntil field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetPremiumUntil() int64 {
	if o == nil || IsNil(o.PremiumUntil) {
		var ret int64
		return ret
	}
	return *o.PremiumUntil
}

// GetPremiumUntilOk returns a tuple with the PremiumUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetPremiumUntilOk() (*int64, bool) {
	if o == nil || IsNil(o.PremiumUntil) {
		return nil, false
	}
	return o.PremiumUntil, true
}

// HasPremiumUntil returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasPremiumUntil() bool {
	if o != nil && !IsNil(o.PremiumUntil) {
		return true
	}

	return false
}

// SetPremiumUntil gets a reference to the given int64 and assigns it to the PremiumUntil field.
func (o *V4UserGet200ResponseDataUser) SetPremiumUntil(v int64) {
	o.PremiumUntil = &v
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetLang() string {
	if o == nil || IsNil(o.Lang) {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetLangOk() (*string, bool) {
	if o == nil || IsNil(o.Lang) {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasLang() bool {
	if o != nil && !IsNil(o.Lang) {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *V4UserGet200ResponseDataUser) SetLang(v string) {
	o.Lang = &v
}

// GetPreferedDomain returns the PreferedDomain field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetPreferedDomain() string {
	if o == nil || IsNil(o.PreferedDomain) {
		var ret string
		return ret
	}
	return *o.PreferedDomain
}

// GetPreferedDomainOk returns a tuple with the PreferedDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetPreferedDomainOk() (*string, bool) {
	if o == nil || IsNil(o.PreferedDomain) {
		return nil, false
	}
	return o.PreferedDomain, true
}

// HasPreferedDomain returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasPreferedDomain() bool {
	if o != nil && !IsNil(o.PreferedDomain) {
		return true
	}

	return false
}

// SetPreferedDomain gets a reference to the given string and assigns it to the PreferedDomain field.
func (o *V4UserGet200ResponseDataUser) SetPreferedDomain(v string) {
	o.PreferedDomain = &v
}

// GetFidelityPoints returns the FidelityPoints field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetFidelityPoints() int64 {
	if o == nil || IsNil(o.FidelityPoints) {
		var ret int64
		return ret
	}
	return *o.FidelityPoints
}

// GetFidelityPointsOk returns a tuple with the FidelityPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetFidelityPointsOk() (*int64, bool) {
	if o == nil || IsNil(o.FidelityPoints) {
		return nil, false
	}
	return o.FidelityPoints, true
}

// HasFidelityPoints returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasFidelityPoints() bool {
	if o != nil && !IsNil(o.FidelityPoints) {
		return true
	}

	return false
}

// SetFidelityPoints gets a reference to the given int64 and assigns it to the FidelityPoints field.
func (o *V4UserGet200ResponseDataUser) SetFidelityPoints(v int64) {
	o.FidelityPoints = &v
}

// GetLimitedHostersQuotas returns the LimitedHostersQuotas field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetLimitedHostersQuotas() map[string]int64 {
	if o == nil || IsNil(o.LimitedHostersQuotas) {
		var ret map[string]int64
		return ret
	}
	return *o.LimitedHostersQuotas
}

// GetLimitedHostersQuotasOk returns a tuple with the LimitedHostersQuotas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetLimitedHostersQuotasOk() (*map[string]int64, bool) {
	if o == nil || IsNil(o.LimitedHostersQuotas) {
		return nil, false
	}
	return o.LimitedHostersQuotas, true
}

// HasLimitedHostersQuotas returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasLimitedHostersQuotas() bool {
	if o != nil && !IsNil(o.LimitedHostersQuotas) {
		return true
	}

	return false
}

// SetLimitedHostersQuotas gets a reference to the given map[string]int64 and assigns it to the LimitedHostersQuotas field.
func (o *V4UserGet200ResponseDataUser) SetLimitedHostersQuotas(v map[string]int64) {
	o.LimitedHostersQuotas = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *V4UserGet200ResponseDataUser) GetNotifications() []string {
	if o == nil || IsNil(o.Notifications) {
		var ret []string
		return ret
	}
	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4UserGet200ResponseDataUser) GetNotificationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *V4UserGet200ResponseDataUser) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given []string and assigns it to the Notifications field.
func (o *V4UserGet200ResponseDataUser) SetNotifications(v []string) {
	o.Notifications = v
}

func (o V4UserGet200ResponseDataUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V4UserGet200ResponseDataUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.IsPremium) {
		toSerialize["isPremium"] = o.IsPremium
	}
	if !IsNil(o.IsSubscribed) {
		toSerialize["isSubscribed"] = o.IsSubscribed
	}
	if !IsNil(o.IsTrial) {
		toSerialize["isTrial"] = o.IsTrial
	}
	if !IsNil(o.PremiumUntil) {
		toSerialize["premiumUntil"] = o.PremiumUntil
	}
	if !IsNil(o.Lang) {
		toSerialize["lang"] = o.Lang
	}
	if !IsNil(o.PreferedDomain) {
		toSerialize["preferedDomain"] = o.PreferedDomain
	}
	if !IsNil(o.FidelityPoints) {
		toSerialize["fidelityPoints"] = o.FidelityPoints
	}
	if !IsNil(o.LimitedHostersQuotas) {
		toSerialize["limitedHostersQuotas"] = o.LimitedHostersQuotas
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	return toSerialize, nil
}

type NullableV4UserGet200ResponseDataUser struct {
	value *V4UserGet200ResponseDataUser
	isSet bool
}

func (v NullableV4UserGet200ResponseDataUser) Get() *V4UserGet200ResponseDataUser {
	return v.value
}

func (v *NullableV4UserGet200ResponseDataUser) Set(val *V4UserGet200ResponseDataUser) {
	v.value = val
	v.isSet = true
}

func (v NullableV4UserGet200ResponseDataUser) IsSet() bool {
	return v.isSet
}

func (v *NullableV4UserGet200ResponseDataUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4UserGet200ResponseDataUser(val *V4UserGet200ResponseDataUser) *NullableV4UserGet200ResponseDataUser {
	return &NullableV4UserGet200ResponseDataUser{value: val, isSet: true}
}

func (v NullableV4UserGet200ResponseDataUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4UserGet200ResponseDataUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
